#!/bin/bash
# thanks https://stackoverflow.com/questions/54578066/how-to-build-a-docker-image-on-a-specific-architecture-with-docker-hub.
# Register qemu-*-static for all supported processors except the current one, but also remove all registered binfmt_misc before
