name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=seconds | sed 's/ /T/g')" >> ${GITHUB_ENV}

      - name: Check out the repo
        uses: actions/checkout@v4


      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_API_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ vars.ORGANIZATION }}/${{ vars.REPOSITORY }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

      # Needed for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Needed for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./build/package/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
              "APPLICATION=${{ github.event.repository.name }}"
              "BUILD_RFC3339=${{ env.RELEASE_DATE }}"
              DESCRIPTION="${{ github.event.repository.description }}"
              "PACKAGE=${{ github.repository }}"
              "REVISION=${{ github.sha }}"
              "VERSION=${{ github.ref_name }}"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}